import type { Player, Team, OffseasonMove } from '../../types';
import heatles2011Players from './heatles-2010-11/players.json';
import heatles2011Teams from './heatles-2010-11/teams.json';
import heatles2011Moves from './heatles-2010-11/offseason_moves.json';
import heatles2011Draft from './heatles-2010-11/draft_class.json';
import lockout2012Players from './lockout-2011-12/players.json';
import lockout2012Teams from './lockout-2011-12/teams.json';
import lockout2012Moves from './lockout-2011-12/offseason_moves.json';
import lockout2012Draft from './lockout-2011-12/draft_class.json';
import threepeat2013Players from './threepeat-2012-13/players.json';
import threepeat2013Teams from './threepeat-2012-13/teams.json';
import threepeat2013Moves from './threepeat-2012-13/offseason_moves.json';
import threepeat2013Draft from './threepeat-2012-13/draft_class.json';
import beautifulGame2014Players from './beautiful-game-2013-14/players.json';
import beautifulGame2014Teams from './beautiful-game-2013-14/teams.json';
import beautifulGame2014Moves from './beautiful-game-2013-14/offseason_moves.json';
import beautifulGame2014Draft from './beautiful-game-2013-14/draft_class.json';
import warriors2015Players from './warriors-2014-15/players.json';
import warriors2015Teams from './warriors-2014-15/teams.json';
import warriors2015Moves from './warriors-2014-15/offseason_moves.json';
import warriors2015Draft from './warriors-2014-15/draft_class.json';
import lebron2016Players from './lebron-2015-16/players.json';
import lebron2016Teams from './lebron-2015-16/teams.json';
import lebron2016Moves from './lebron-2015-16/offseason_moves.json';
import lebron2016Draft from './lebron-2015-16/draft_class.json';
import durantWarriors2017Players from './durant-warriors-2016-17/players.json';
import durantWarriors2017Teams from './durant-warriors-2016-17/teams.json';
import durantWarriors2017Moves from './durant-warriors-2016-17/offseason_moves.json';
import durantWarriors2017Draft from './durant-warriors-2016-17/draft_class.json';
import rockets2018Players from './rockets-2017-18/players.json';
import rockets2018Teams from './rockets-2017-18/teams.json';
import rockets2018Moves from './rockets-2017-18/offseason_moves.json';
import rockets2018Draft from './rockets-2017-18/draft_class.json';
import raptors2019Players from './raptors-2018-19/players.json';
import raptors2019Teams from './raptors-2018-19/teams.json';
import raptors2019Moves from './raptors-2018-19/offseason_moves.json';
import raptors2019Draft from './raptors-2018-19/draft_class.json';
import bubble2020Players from './bubble-2019-20/players.json';
import bubble2020Teams from './bubble-2019-20/teams.json';
import bubble2020Moves from './bubble-2019-20/offseason_moves.json';

// A registry of playable historical starting points ("NBA Eras"). Each entry
// is a self-contained real roster/rating snapshot generated by
// nba-gm-simulator/pipeline/fetch_data.py --season <X> --skip-offseason-moves
// --out data/eras/<id> — the SAME pipeline/rating model the live current-season
// data uses, just pointed at a past season instead of today's.
//
// This is a SNAPSHOT, not a time machine: picking an era only changes what
// initSeason (App.tsx) seeds SeasonState.players/teams with. From team
// confirmation onward the save plays with 100% of today's mechanics —
// procedural free agency, trades, progression — nothing here re-simulates
// real NBA history going forward, with two chained EXCEPTIONS: offseasonMoves
// (real trades/signings) and realDraftClass (real rookies) below.
//
// Seasons before 2015-16 predate the NBA's hustle-stats tracking (and
// 2013-14/2014-15 predate full player-tracking defense), so the pipeline's
// perimeterD/interiorD attributes lean more on steals/blocks/rebound% alone
// for those years — ratings are still real-stat-driven, just slightly less
// granular on the defensive breakdown. teams.json names were hand-corrected
// for franchises that later renamed/relocated (New Jersey Nets → Brooklyn,
// Charlotte Bobcats → Hornets, New Orleans Hornets → Pelicans) so each era
// shows the name the team actually played under that season; logos still use
// the current franchise crest since no historical crest is hosted at the CDN
// this app pulls from.
//
// Each era is its own static import (Metro can't resolve a JSON path built
// from a runtime variable), so adding a new era means adding a matching
// `data/eras/<id>/` folder on disk with all four imports (players/teams/
// offseason_moves/draft_class) here.
export interface EraDefinition {
  id: string;
  label: string;
  seasonLabel: string;
  /** One-line flavor text shown on the era picker. */
  blurb: string;
  players: { [key: string]: Player };
  teams: Team[];
  // Real trades/signings between THIS era's season and the next chronological
  // era's — generated by pipeline/sync_era_moves.py (nba-gm-simulator), which
  // diffs this era's on-disk roster against next season's real NBA rosters
  // (same mechanism the live current-season data uses for its own one-shot
  // replay, see offseasonMoves in App.tsx). App.tsx's handleStartNewSeason
  // walks the ERAS array forward one entry per in-save offseason
  // (SeasonState.eraChainIndex), so an era save keeps replaying real history
  // year over year instead of being a single disconnected snapshot. The last
  // chronological entry (bubble-2019-20) has an empty list — no further
  // chained season was pulled — which is also what any entry naturally
  // degrades to once the user's own moves have diverged the save from real
  // history (each move is skipped individually if it no longer matches
  // current save state).
  offseasonMoves: { fromSeason: string; toSeason: string; moves: OffseasonMove[] };
  // The REAL draft class entering the league at this era's chained
  // transition — generated by pipeline/sync_era_draft.py, which pulls the
  // real round-1 order (nba_api's drafthistory) and cross-references each
  // pick's rookie-year rating against the NEXT era's already-fetched
  // players.json (a rookie's real attribute breakdown already exists there
  // the moment that next season was pulled — no separate rating step).
  // `playerId` is null for a pick that never cleared the rating pipeline's
  // minimum GP/MPG as a rookie (hurt, stashed overseas, D-League); the app
  // substitutes one procedural prospect for that single slot, same
  // per-item fallback the offseason-moves chain already uses. Deliberately
  // carries no team info — WHICH team lands each pick stays driven by this
  // save's own standings/lottery, not real history's; only WHO enters the
  // league and their real rating is replayed. Undefined for bubble-2019-20
  // (no further chained season was pulled) — the chain naturally goes fully
  // procedural once this runs out, same as offseasonMoves.
  realDraftClass?: { draftYear: string; picks: { overallPick: number; playerId: string | null; playerName: string }[] };
}

export const ERAS: EraDefinition[] = [
  {
    id: 'heatles-2010-11',
    label: 'Heatles',
    seasonLabel: '2010-11',
    blurb: 'LeBron, Wade e Bosh se juntam em Miami — e esbarram no Dirk dos Mavericks na final.',
    players: heatles2011Players as unknown as { [key: string]: Player },
    teams: heatles2011Teams as unknown as Team[],
    offseasonMoves: heatles2011Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: heatles2011Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'lockout-2011-12',
    label: 'Temporada do Lockout',
    seasonLabel: '2011-12',
    blurb: 'Só 66 jogos, LeBron MVP e o primeiro título do Heat.',
    players: lockout2012Players as unknown as { [key: string]: Player },
    teams: lockout2012Teams as unknown as Team[],
    offseasonMoves: lockout2012Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: lockout2012Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'threepeat-2012-13',
    label: 'Heat Bicampeão',
    seasonLabel: '2012-13',
    blurb: '27 vitórias seguidas e o segundo anel consecutivo de LeBron.',
    players: threepeat2013Players as unknown as { [key: string]: Player },
    teams: threepeat2013Teams as unknown as Team[],
    offseasonMoves: threepeat2013Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: threepeat2013Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'beautiful-game-2013-14',
    label: 'O Jogo Bonito',
    seasonLabel: '2013-14',
    blurb: 'Spurs de Popovich e Duncan destroem o Heat na revanche das Finais.',
    players: beautifulGame2014Players as unknown as { [key: string]: Player },
    teams: beautifulGame2014Teams as unknown as Team[],
    offseasonMoves: beautifulGame2014Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: beautifulGame2014Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'warriors-2014-15',
    label: 'Início da Dinastia',
    seasonLabel: '2014-15',
    blurb: 'Steve Kerr assume e o Warriors de Curry conquista o primeiro título da era.',
    players: warriors2015Players as unknown as { [key: string]: Player },
    teams: warriors2015Teams as unknown as Team[],
    offseasonMoves: warriors2015Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: warriors2015Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'lebron-2015-16',
    label: 'LeBron Era',
    seasonLabel: '2015-16',
    blurb: 'Warriors 73-9, o Big Three do Heat já dissolvido, LeBron de volta a Cleveland.',
    players: lebron2016Players as unknown as { [key: string]: Player },
    teams: lebron2016Teams as unknown as Team[],
    offseasonMoves: lebron2016Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: lebron2016Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'durant-warriors-2016-17',
    label: 'A Revanche',
    seasonLabel: '2016-17',
    blurb: 'Durant se junta a Curry depois do 3-1 perdido — Warriors imparáveis.',
    players: durantWarriors2017Players as unknown as { [key: string]: Player },
    teams: durantWarriors2017Teams as unknown as Team[],
    offseasonMoves: durantWarriors2017Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: durantWarriors2017Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'rockets-2017-18',
    label: 'O Ano do MVP Harden',
    seasonLabel: '2017-18',
    blurb: 'Rockets de 65 vitórias quase derrubam a dinastia Warriors na final de conferência.',
    players: rockets2018Players as unknown as { [key: string]: Player },
    teams: rockets2018Teams as unknown as Team[],
    offseasonMoves: rockets2018Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: rockets2018Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'raptors-2018-19',
    label: 'O Ano do Kawhi',
    seasonLabel: '2018-19',
    blurb: 'Leonard chega em Toronto e entrega o primeiro título da franquia.',
    players: raptors2019Players as unknown as { [key: string]: Player },
    teams: raptors2019Teams as unknown as Team[],
    offseasonMoves: raptors2019Moves as unknown as EraDefinition['offseasonMoves'],
    realDraftClass: raptors2019Draft as unknown as EraDefinition['realDraftClass'],
  },
  {
    id: 'bubble-2019-20',
    label: 'A Bolha',
    seasonLabel: '2019-20',
    blurb: 'Temporada em Orlando pós-pandemia: LeBron e AD vencem em homenagem a Kobe.',
    players: bubble2020Players as unknown as { [key: string]: Player },
    teams: bubble2020Teams as unknown as Team[],
    offseasonMoves: bubble2020Moves as unknown as EraDefinition['offseasonMoves'],
    // No draft_class.json for this era — no further chained season was pulled.
  },
];

export const eraById = (id: string): EraDefinition | undefined => ERAS.find((e) => e.id === id);
