import type { Player, Team, OffseasonMove } from '../../types';
import heatles2011Players from './heatles-2010-11/players.json';
import heatles2011Teams from './heatles-2010-11/teams.json';
import lockout2012Players from './lockout-2011-12/players.json';
import lockout2012Teams from './lockout-2011-12/teams.json';
import threepeat2013Players from './threepeat-2012-13/players.json';
import threepeat2013Teams from './threepeat-2012-13/teams.json';
import beautifulGame2014Players from './beautiful-game-2013-14/players.json';
import beautifulGame2014Teams from './beautiful-game-2013-14/teams.json';
import warriors2015Players from './warriors-2014-15/players.json';
import warriors2015Teams from './warriors-2014-15/teams.json';
import lebron2016Players from './lebron-2015-16/players.json';
import lebron2016Teams from './lebron-2015-16/teams.json';
import durantWarriors2017Players from './durant-warriors-2016-17/players.json';
import durantWarriors2017Teams from './durant-warriors-2016-17/teams.json';
import rockets2018Players from './rockets-2017-18/players.json';
import rockets2018Teams from './rockets-2017-18/teams.json';
import raptors2019Players from './raptors-2018-19/players.json';
import raptors2019Teams from './raptors-2018-19/teams.json';
import bubble2020Players from './bubble-2019-20/players.json';
import bubble2020Teams from './bubble-2019-20/teams.json';

// A registry of playable historical starting points ("NBA Eras"). Each entry
// is a self-contained real roster/rating snapshot generated by
// nba-gm-simulator/pipeline/fetch_data.py --season <X> --skip-offseason-moves
// --out data/eras/<id> — the SAME pipeline/rating model the live current-season
// data uses, just pointed at a past season instead of today's.
//
// This is a SNAPSHOT, not a time machine: picking an era only changes what
// initSeason (App.tsx) seeds SeasonState.players/teams with. From team
// confirmation onward the save plays with 100% of today's mechanics —
// procedural draft class generation, procedural free agency, trades,
// progression — nothing here re-simulates real NBA history going forward.
//
// Seasons before 2015-16 predate the NBA's hustle-stats tracking (and
// 2013-14/2014-15 predate full player-tracking defense), so the pipeline's
// perimeterD/interiorD attributes lean more on steals/blocks/rebound% alone
// for those years — ratings are still real-stat-driven, just slightly less
// granular on the defensive breakdown. teams.json names were hand-corrected
// for franchises that later renamed/relocated (New Jersey Nets → Brooklyn,
// Charlotte Bobcats → Hornets, New Orleans Hornets → Pelicans) so each era
// shows the name the team actually played under that season; logos still use
// the current franchise crest since no historical crest is hosted at the CDN
// this app pulls from.
//
// Each era is its own static import (Metro can't resolve a JSON path built
// from a runtime variable), so adding a new era means adding both a pair of
// imports here and a matching `data/eras/<id>/` folder on disk.
export interface EraDefinition {
  id: string;
  label: string;
  seasonLabel: string;
  /** One-line flavor text shown on the era picker. */
  blurb: string;
  players: { [key: string]: Player };
  teams: Team[];
  // An era save never replays "real" future trades/signings — that only makes
  // sense for the live current-season data, where next season's real moves
  // are actual, already-known history. This is always an empty stub, not the
  // offseason_moves.json the pipeline also writes to disk for the era (which
  // nothing here reads).
  offseasonMoves: { fromSeason: string; toSeason: string; moves: OffseasonMove[] };
}

export const ERAS: EraDefinition[] = [
  {
    id: 'heatles-2010-11',
    label: 'Heatles',
    seasonLabel: '2010-11',
    blurb: 'LeBron, Wade e Bosh se juntam em Miami — e esbarram no Dirk dos Mavericks na final.',
    players: heatles2011Players as unknown as { [key: string]: Player },
    teams: heatles2011Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2010-11', toSeason: '2011-12', moves: [] },
  },
  {
    id: 'lockout-2011-12',
    label: 'Temporada do Lockout',
    seasonLabel: '2011-12',
    blurb: 'Só 66 jogos, LeBron MVP e o primeiro título do Heat.',
    players: lockout2012Players as unknown as { [key: string]: Player },
    teams: lockout2012Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2011-12', toSeason: '2012-13', moves: [] },
  },
  {
    id: 'threepeat-2012-13',
    label: 'Heat Bicampeão',
    seasonLabel: '2012-13',
    blurb: '27 vitórias seguidas e o segundo anel consecutivo de LeBron.',
    players: threepeat2013Players as unknown as { [key: string]: Player },
    teams: threepeat2013Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2012-13', toSeason: '2013-14', moves: [] },
  },
  {
    id: 'beautiful-game-2013-14',
    label: 'O Jogo Bonito',
    seasonLabel: '2013-14',
    blurb: 'Spurs de Popovich e Duncan destroem o Heat na revanche das Finais.',
    players: beautifulGame2014Players as unknown as { [key: string]: Player },
    teams: beautifulGame2014Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2013-14', toSeason: '2014-15', moves: [] },
  },
  {
    id: 'warriors-2014-15',
    label: 'Início da Dinastia',
    seasonLabel: '2014-15',
    blurb: 'Steve Kerr assume e o Warriors de Curry conquista o primeiro título da era.',
    players: warriors2015Players as unknown as { [key: string]: Player },
    teams: warriors2015Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2014-15', toSeason: '2015-16', moves: [] },
  },
  {
    id: 'lebron-2015-16',
    label: 'LeBron Era',
    seasonLabel: '2015-16',
    blurb: 'Warriors 73-9, o Big Three do Heat já dissolvido, LeBron de volta a Cleveland.',
    players: lebron2016Players as unknown as { [key: string]: Player },
    teams: lebron2016Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2015-16', toSeason: '2016-17', moves: [] },
  },
  {
    id: 'durant-warriors-2016-17',
    label: 'A Revanche',
    seasonLabel: '2016-17',
    blurb: 'Durant se junta a Curry depois do 3-1 perdido — Warriors imparáveis.',
    players: durantWarriors2017Players as unknown as { [key: string]: Player },
    teams: durantWarriors2017Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2016-17', toSeason: '2017-18', moves: [] },
  },
  {
    id: 'rockets-2017-18',
    label: 'O Ano do MVP Harden',
    seasonLabel: '2017-18',
    blurb: 'Rockets de 65 vitórias quase derrubam a dinastia Warriors na final de conferência.',
    players: rockets2018Players as unknown as { [key: string]: Player },
    teams: rockets2018Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2017-18', toSeason: '2018-19', moves: [] },
  },
  {
    id: 'raptors-2018-19',
    label: 'O Ano do Kawhi',
    seasonLabel: '2018-19',
    blurb: 'Leonard chega em Toronto e entrega o primeiro título da franquia.',
    players: raptors2019Players as unknown as { [key: string]: Player },
    teams: raptors2019Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2018-19', toSeason: '2019-20', moves: [] },
  },
  {
    id: 'bubble-2019-20',
    label: 'A Bolha',
    seasonLabel: '2019-20',
    blurb: 'Temporada em Orlando pós-pandemia: LeBron e AD vencem em homenagem a Kobe.',
    players: bubble2020Players as unknown as { [key: string]: Player },
    teams: bubble2020Teams as unknown as Team[],
    offseasonMoves: { fromSeason: '2019-20', toSeason: '2020-21', moves: [] },
  },
];

export const eraById = (id: string): EraDefinition | undefined => ERAS.find((e) => e.id === id);
